resolver: nightly-2018-08-29
extra-package-dbs: []
flags: {}
packages:
  - '.'
extra-deps:
- 'hakyll-4.12.3.0'
- 'pandoc-2.1.3'
- 'JuicyPixels-3.2.9.5'
- 'aeson-1.3.1.1'
- 'file-embed-0.0.10.1'
- 'haddock-library-1.5.0.1'
- 'pandoc-citeproc-0.14.3.1'
- 'temporary-1.2.1.1'
- 'texmath-0.10.1.2'
- 'yaml-0.8.32'
- 'rfc5051-0.1.0.3'
